# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  schedule:
    - cron:  '37 2 * * 6'

name: backup-and-upload

jobs:
  backup-and-upload:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Get date
        id: date
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create archives
        env:
          GITHUB_PAT: ${{ secrets.BACKUP_PAT }}
        run: |
          gitcellar::download_organization_repos(
            c("epiverse-trace", "epiverse-connect"),
            dest_folder = "${{ steps.date.outputs.TODAY }}-backup"
          )
        shell: Rscript {0}

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.JSON_KEY }}

      - uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: '${{ steps.date.outputs.TODAY }}-backup'
          destination: 'epiverse-backups'
